export const GET_SHOWTIME_DETIAL = "GET_SHOWTIME_DETIAL";
export const SELECT_SEAT = "SELECT_SEAT";
export const DONE_BOOKING_TICKET = "DONE_BOOKING_TICKET";
export const GET_LST_SEAT_REALTIME = "GET_LST_SEAT_REALTIME";
export const CLEAR_SEAT_OVERTIME = "CLEAR_SEAT_OVERTIME"