export const GET_BANNER = "GET_BANNER";
export const GET_ALL_FILM_INFO = "GET_ALL_FILM_INFO";
export const GET_FILM_NOWSHOWING = "GET_FILM_NOWSHOWING";
export const GET_FILM_COMINGSOON = "GET_FILM_COMINGSOON";